input_folder: "cpdatacards/wham_phi_cp"
output_folder: "outputs/wham_phi_cp"
channels: ["tt"]
merge_mode: 0
input_file_pattern: "added_histo_{channel}-mergeXbins.root"

systematics: false
auto_mc_stats: false

categories:
  tt:
    - [3, tt_higgs_rhorho]
    - [7, tt_higgs_pirho]
    - [8, tt_higgs_pipi]
    - [9, tt_higgs_pia1]
    - [12, tt_higgs_rhopi]
    - [13, tt_higgs_rhoa1]
    - [14, tt_higgs_a1pi]
    - [15, tt_higgs_a1rho]
    - [16, tt_higgs_a1a1]

backgrounds:
  tt:
    - DY_2Tau

signals:
  ggH:
    - ggH_sm_prod_sm_htt
    - ggH_ps_prod_sm_htt

t2w_physics_options:
  - linear_alpha
  - fix_signal_strengths

alpha_scan:
  set_parameters: {alpha: 0}
  range: [0, 1]
  points: 21
  name: ".alpha"
  plot: {x_min: 0, x_max: 1, y_max: 8}
